FROM python:3.5.1
LABEL maintainer="Evoniners <dev@evonove.it>"

ENV DJANGO_SETTINGS_MODULE=jewels.settings.production \
    DJANGO_DEBUG=False

EXPOSE 8000

WORKDIR /app

ADD ./requirements/requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app
COPY containers/start.sh /usr/local/bin

ENTRYPOINT ["start.sh"]
CMD ["uwsgi"]
